language: python
python:
    - "3.6"
    - "pypy3.6-7.1.1"

cache:
    pip: true

install:
    - pip install codecov

jobs:
    include:
        - python: "3.6"
          stage: test
          install:
            - pip install -r requirements.txt
          script:
              - echo "pypy3 version $(pypy3 --version) running"
              - echo "pip version $(pip --version) running"
              - make check
        - python: "pypy3.6-7.1.1"
          install:
              - pip install -r requirements.txt
          stage: test
            - echo "pypy3 version $(pypy3 --version) running"
            - echo "pip version $(pip --version) running"
            - make coverage

after_success:
  - codecov -t 452b6965-c9da-4306-97d5-a5e86626af8f

