language: python
python:
    - "3.6"

cache:
    pip: true

install:
    - pip install -r requirements.txt
    - pip install codecov

jobs:
    include:
        - stage: test
          script:
              - echo "python version $(python --version) running"
              - echo "pip version $(pip --version) running"
              - make check coverage

after_success:
  - codecov -t 452b6965-c9da-4306-97d5-a5e86626af8f

