language: python
python:
    - "3.6"
    - "pypy3.6-7.1.1"

cache:
    pip: true

install:
    - pip install codecov

jobs:
    include:
        - python: ["3.6", "pypy3.6-7.1.1"]
          stage: test
          script:
              - echo "pypy3 version $(pypy3 --version) running"
              - echo "pip version $(pip --version) running"
              # Awful hack -- there's probably a better way to do this in Travis
              - if (type -P pypy3) ; then make check; else make coverage; fi
        - python: "3.6"
          install:
              - pip install -r requirements.txt
        - python: "pypy3.6-7.1.1"
          install:
              - pip install -r requirements_pypy.txt

after_success:
  - codecov -t 452b6965-c9da-4306-97d5-a5e86626af8f

